name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test

